language: ruby
cache: bundler
branches:
  only:
  - release
script:
  - bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: ./_site
  fqdn: hyeon.io
  on:
    branch: release
