title      : 성기현 노트
description: |
  개인적인 생각과 자료를 정리하는 노트입니다.

  잘못된 내용이나 오탈자가 있을 수 있습니다. 연락 주시면 감사히 수정하겠습니다.
url    : https://hyeon.io
static : /static
media  : /media
exclude:
  - LICENSE

timezome: Asia/Seoul

defaults:
  - scope:
      path: _notes
    values:
      layout  : note
      category: index

collections:
  notes:
    output   : true
    permalink: /:path

algolia:
  application_id     : OLMCPSMD9N
  index_name         : notes
  search_only_api_key: 040c121385e2b9a86935cdb74ef87d55

katex:
  rendering_options:
    throw_error: true
    error_color: "#ff0000"
