title      : 성기현의 개인 위키
description: |
  개인적인 생각과 자료를 정리하는 위키입니다.

  잘못된 내용이나 오탈자가 있을 수 있습니다. 연락 주시면 감사히 수정하겠습니다.
url    : https://wiki.hyeon.io
static : /static
media  : /media
exclude:
  - LICENSE

timezome: Asia/Seoul

defaults:
  - scope:
      path: _docs
    values:
      layout  : doc
      category: 대문

collections:
  docs:
    output   : true
    permalink: /:path
