title: 노트
description: >-
  개인적으로 공부하고 찾은 자료를 정리합니다.

url: "https://hyeon.io"

timezome: Asia/Seoul

static: /static
media: /media

plugins:
  - jekyll-katex

katex:
  rendering_options:
    throw_error: true
    error_color: "#ff0000"

defaults:
  -
    scope:
      path: "_notes"
    values:
      layout: "note"
      category: "index"

collections:
  notes:
    output: true
    permalink: /:collection/:slug
