title: 노트
description: 공부하고 찾은 자료를 정리합니다.
timezome: Asia/Seoul
url: https://hyeon.io

static: /static
media: /media
exclude:
  - LICENSE

defaults:
  - scope:
      path: _notes
    values:
      layout: note
      category: index
collections:
  notes:
    output: true
    permalink: /:collection/:path

plugins:
  - jekyll-katex
katex:
  rendering_options:
    throw_error: true
    error_color: "#ff0000"
