title: 성기현 노트
description: >-
  아무거나 기록

baseurl: ""
url: "https://hyeon.io"

timezome: Asia/Seoul

static: /static
media: /media

plugins:
  - jekyll-katex
  - jekyll-sitemap
  - jekyll-toc

katex:
  rendering_options:
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"                  # errorColor

defaults:
  -
    scope:
      path: "_notes"
    values:
      layout: "note"
      toc: true
      category: "root"

collections:
  notes:
    output: true
    permalink: /:collection/:slug
