title: 성기현 블로그
description: >-
  생각과 열정을 기록한 곳입니다.

baseurl: ""
url: "https://hyeon.io"

timezome: Asia/Seoul

static: /static
media: /media

plugins:
  - jekyll-feed
  - jekyll-katex
  - jekyll-sitemap

katex:
  rendering_options:
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"                  # errorColor
