name: "성기현 블로그"
description: "아무거나 기록"

url: '' 
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-katex

katex:
  rendering_options:
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"                  # errorColor

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

