url    : https://gihyeon.xyz
static : /static
exclude:
  - LICENSE

timezome: Asia/Seoul

defaults:
  - scope:
      path: _docs
    values:
      layout  : doc
      category: 대문

collections:
  docs:
    output   : true
    permalink: /:title
