title      : 성기현의 개인 위키
description: 개인적인 생각과 자료를 정리하는 위키입니다.
url        : https://gihyeon.xyz
static     : /static
media      : /media
exclude    :
  - LICENSE

timezome: Asia/Seoul

defaults:
  - scope:
      path: _docs
    values:
      layout  : doc
      category: 대문

collections:
  docs:
    output   : true
    permalink: /:title
