# Setup
title:        성기현 블로그       
tagline:      아무거나 기록
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Gihyeon Sung
  url:        https://github.com/chu-tty

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
