on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps  :
      - name: Get wiki repository
        uses: actions/checkout@v2

      - name: Setup Ruby for Jekyll
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.1'

      - name: Setup cache for Bundle plugins
        uses: actions/cache@v1
        with:
          path        : vendor/bundle
          key         : ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Build wiki
        run : |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec jekyll build
          bundle exec jekyll build

      - name: Push content to Algolia indices
        run : bundle exec jekyll algolia
        env :
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token  : ${{ secrets.GITHUB_TOKEN }}
          publish_dir   : ./_site
          publish_branch: master
